### ISSUE TITLE
Inline?

### ISSUE THREAD

**Issue by jeffRTC** [endreymarcell/esbuild-plugin-webworker#1]
Does this plugin emit inlined worker? 

I am searching for a plugin that emit inlined worker (including all the requires) because my custom env doesn't supports separate files.

**Comment by endreymarcell** [comment]
No, this plugin emits the worker as a separate file.

**Comment by jeffRTC** [comment]
Do you have any plan to make it inline?

Can't find any and would be super useful.

**Comment by endreymarcell** [comment]
No such plans. I just wrote this piece of code because I needed it for my work and shared it in a repo thinking it might be useful for others too, but I'm not improving/developing it further.
